### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by Lectem** [nickbruun/hayai#26]
It would be nice if you could detect overflows and you are doing your calculations, I ended up having negative value and even very small ones in cases where the test lasts for a while (on low performance hardware).
I suggest starting by using uint64_t instead of signed values, and detect overflows when computing the average times.
I also think you should keep us and s seperated.

**Comment by nickbruun** [comment]
Can you give me an example of this output?

**Comment by nickbruun** [comment]
@Lectem can you provide an example as per the question above?

**Comment by Lectem** [comment]
I will try to find my test again, and will update the issue with the code

**Comment by Lectem** [comment]
The test overflows on 32bit arch (tested on 32bit arm) but not on my 64-bit (x86 CPU).

I found the issue and fixed it with https://github.com/nickbruun/hayai/pull/29 .

A test that could show this behaviour is


    #include <hayai.hpp>
    BENCHMARK(overflow,bug,100,50)
    {
        usleep(150541);
    }

It could probably be made shorter though. The results used to be :

    [==========] Running 1 benchmark..
    [ RUN      ] overflow.bug (100 runs, 50 iterations per run)
    [     DONE ] overflow.bug (-58970.656200 ms)
    [   RUNS   ]        Average time: -589706.562 us
                         Fastest: -595866.592 us (-6160.030 us / 1.045 %)
                         Slowest: -582545.592 us (+7160.970 us / +-1.214 %)
                                  
             Average performance: -1.69576 runs/s
                Best performance: -1.67823 runs/s (+0.01753 runs/s / +-1.03379 %)
               Worst performance: -1.71660 runs/s (-0.02085 runs/s / 1.22925 %)
    [ITERATIONS]        Average time: -11794.131 us
                         Fastest: -11917.332 us (-123.201 us / 1.045 %)
                         Slowest: -11650.912 us (+143.219 us / +-1.214 %)
                                  
             Average performance: -84.78793 iterations/s
                Best performance: -83.91140 iterations/s (+0.87653 iterations/s / +-1.03379 %)
               Worst performance: -85.83019 iterations/s (-1.04226 iterations/s / 1.22925 %)
    [==========] Ran 1 benchmark..

**Comment by nickbruun** [comment]
Solid catch. Thank you :)
