### ISSUE TITLE
How to access benchmark test results after running the tests?

### ISSUE THREAD

**Issue by warbaque** [nickbruun/hayai#36]
Very simple piece of example code:
https://bpaste.net/show/7df01dce723f

How can I access benchmark values after running the tests? For example if I needed average iteration times from multiple tests for further analysis?

**Comment by nickbruun** [comment]
Hi,

If you're linking with hayai_main, you can run the executable with `--help` after compiling it to see output methods. For the most precise data, you'd probably want to use the JSON output:

    $ ./mybenchmarks -o json:result.json

For now you'll have to refer to https://github.com/nickbruun/hayai/blob/master/src/hayai_json_outputter.hpp#L24 for a format specification. I really need to get proper documentation written ASAP :)
