### ISSUE TITLE
Warnings on Visual Studio 2013

### ISSUE THREAD

**Issue by acnazarejr** [nickbruun/hayai#40]
warning C4244: 'return' : conversion from 'const uint64_t' to 'double', possible loss of data	hayai_test_result.hpp line 52

warning C4244: 'return' : conversion from 'const uint64_t' to 'double', possible loss of data	hayai_test_result.hpp line 73

warning C4244: 'return' : conversion from 'const uint64_t' to 'double', possible loss of data	hayai_test_result.hpp line 80

**Comment by nickbruun** [comment]
Fixed by #41
