### ISSUE TITLE
Iteration statistics are an average of each run

### ISSUE THREAD

**Issue by nickwinder** [nickbruun/hayai#60]
As each iteration result is not kept in https://github.com/nickbruun/hayai/blob/9ca0833723ffe1af5b71050fd2e4f87a4c4eee11/src/hayai_test_result.hpp#L292-L301, the statistics that are outputted for `ITERATIONS` are only an average of each run. This renders the information rather useless as `ITERATIONS` are only a multiple of the `RUNS` result. 

For example the following benchmark you would expect to see a large variation in each iteration.

```
#include "hayai.hpp"

int g_sleep = 0;

class SleepFixture : public ::hayai::Fixture {
public:
    virtual void SetUp() {
        g_sleep += 10000;
        std::cout << "SetUp " << g_sleep << std::endl;
        usleep(g_sleep);
    }

    virtual void TearDown() {
        g_sleep += 10000;
        std::cout << "TearDown " << g_sleep << std::endl;
        usleep(g_sleep);
    }

    void foo() {
        g_sleep += 10000;
        std::cout << "Sleep " << g_sleep << std::endl;
        usleep(g_sleep);
    }
};

BENCHMARK_F(SleepFixture, Sleeping, 1, 10) {
    foo();
}
```

Whereas the result shows.

```
[==========] Running 1 benchmark..
[ RUN      ] SleepFixture.Sleeping (1 run, 10 iterations per run)
SetUp 10000
Sleep 20000
Sleep 30000
Sleep 40000
Sleep 50000
Sleep 60000
Sleep 70000
Sleep 80000
Sleep 90000
Sleep 100000
Sleep 110000
TearDown 120000
[     DONE ] SleepFixture.Sleeping (676.609770 ms)
[   RUNS   ]        Average time: 676609.770 us (~nan us)
                    Fastest time: 676609.770 us (0.000 us / 0.000 %)
                    Slowest time: 676609.770 us (0.000 us / 0.000 %)
                     Median time: 0.000 us (1st quartile: 676609.770 us | 3rd quartile: 676609.770 us)
                                  
             Average performance: 1.47796 runs/s
                Best performance: 1.47796 runs/s (0.00000 runs/s / 0.00000 %)
               Worst performance: 1.47796 runs/s (0.00000 runs/s / 0.00000 %)
              Median performance: inf runs/s (1st quartile: 1.47796 | 3rd quartile: 1.47796)
                                  
[ITERATIONS]        Average time: 67660.977 us (~nan us)
                    Fastest time: 67660.977 us (0.000 us / 0.000 %)
                    Slowest time: 67660.977 us (0.000 us / 0.000 %)
                     Median time: 0.000 us (1st quartile: 67660.977 us | 3rd quartile: 67660.977 us)
                                  
             Average performance: 14.77957 iterations/s
                Best performance: 14.77957 iterations/s (0.00000 iterations/s / 0.00000 %)
               Worst performance: 14.77957 iterations/s (0.00000 iterations/s / 0.00000 %)
              Median performance: inf iterations/s (1st quartile: 14.77957 | 3rd quartile: 14.77957)
[==========] Ran 1 benchmark..
```

There is no variation in the iterations as this has been averaged away. An example of this can be seen in https://github.com/nickbruun/hayai/blob/9ca0833723ffe1af5b71050fd2e4f87a4c4eee11/src/hayai_test_result.hpp#L243-L246

Is this a design decision or would it be more ideal to keep the data from each iteration and use this information to collate the minimum, maximum, etc?

**Comment by nickbruun** [comment]
This is a design choice, yes, as the performance penalty of measuring each iteration would in many cases be a significant portion of the computational time, given the need for a system call to get the monotonic clock value. It's important to keep in mind, that this is built for microbenchmarks and up, meaning that you have the ability to set the number of measured iterations with the run dimension, and the number of iterations averaged to reduce the error from measurement with the iteration dimension.
