### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jansende** [nickbruun/hayai#61]
Hi,
this is a very interesting project. I would like to try and use at work. However, personal licenses are not compatible with our work policies. Would you be willing to change the license to something well established? For example one of [these](https://choosealicense.com/licenses/)? The [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/) seems to be what you are aiming for... Unfortunately without the beer 😄 

Thanks for considering!

**Comment by nickbruun** [comment]
Legal doesn't consider _Beerware_ a license? ;) Yea, Apache License 2.0 is what I have generally used elsewhere, so that's hereby done for any releases going forward.

**Comment by jansende** [comment]
Thank you very much!
