### ISSUE TITLE
Not able to install hayai from Ubuntu ppa (I run Ubuntu 20.04 focal fossa)

### ISSUE THREAD

**Issue by George-Creekbed** [nickbruun/hayai#63]
Trying with `sudo apt-add-repository ppa:bruun/hayai`
Yielding error : 
`Err:5 http://ppa.launchpad.net/bruun/hayai/ubuntu focal Release                
  404  Not Found [IP: 185.125.190.52 80]`      ... then further down:
`E: The repository 'http://ppa.launchpad.net/bruun/hayai/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
`

**Comment by nickbruun** [comment]
There are no published packages for newer versions of Ubuntu, unfortunately, and I don't think we have anyone with the bandwidth to maintain it. Your best bet here is to build it from scratch.

**Comment by George-Creekbed** [comment]
Thank you and apologies for the insistence. I am no expert on hosting issues hence was not aware of them.
